baseURL: https://workflowr.io/
languageCode: en-us
title: workflowr.io
taxonomies:
  publication: publications
  topic: topics
Paginate: 10

privacy:
  youtube:
    privacyEnhanced: true

params:
  description: Discover reproducible research projects
  images:
  - https://raw.githubusercontent.com/workflowr/workflowr-assets/main/img/workflowr-open-graph.png
  title: workflowr.io

# Related content
# https://gohugo.io/content-management/related/#default-configuration
related:
  threshold: 50
  includeNewer: true
  toLower: true
  indices:
  - name: topics
    weight: 100
  - name: title
    weight: 50
  - name: description
    weight: 50
  - name: account
    weight: 25
  - name: date
    weight: 25

# To allow raw HTML in publication titles
markup:
  goldmark:
    renderer:
      unsafe: true
